### PR TITLE
feat: enable use of `cog verify` in action

### PR DESCRIPTION
**Pull request by the-wondersmith**
PR adds support for using cocogitto's [`verify`](https://docs.cocogitto.io/guide/#sandbox) functionality as part of a down-stream Action

### CODE REVIEW

**Comment by the-wondersmith** [comment]
@oknozor 👋 hello again 😅

**Comment by oknozor** [comment]
> @oknozor wave hello again sweat_smile

Hey @the-wondersmith 
thanks for the PR. I'll be away for a week, I'll take a look as soon as I am back.

**Comment by the-wondersmith** [comment]
> > @oknozor wave hello again sweat_smile
> 
> Hey @the-wondersmith thanks for the PR. I'll be away for a week, I'll take a look as soon as I am back.

@oknozor Shameless self bump

**Comment by the-wondersmith** [comment]
@oknozor Bump

**Comment by oknozor** [comment]
Hey @the-wondersmith I am back, can you rebase this on main so I can merge and release ?

**Comment by the-wondersmith** [comment]
@oknozor Upstream changes pulled in, merge at will 😁

**Comment by oknozor** [comment]
Sorry @the-wondersmith, I just updated the version and there are conflicts again, can you rebase locally so I can merge this ?

**Comment by the-wondersmith** [comment]
@oknozor done and done 😁

**Review by oknozor — APPROVED** [review]

**Comment by oknozor** [comment]
I can't merge, still seeing some conflict. But this seems to be a bug on github.

**Comment by the-wondersmith** [comment]
@oknozor Sorry this apparently took me so long to get back to 😅. Conflicts should be resolved now.

**Comment by the-wondersmith** [comment]
@oknozor bump

**Comment by oknozor** [comment]
@the-wondersmith, the bug is still there: 
image

Can you reopen the same PR from another branch ?

**Comment by the-wondersmith** [comment]
@oknozor rebased locally and force-pushed it (should be just one commit of difference now 😁)

screenshot

**Comment by oknozor** [comment]
hooray ! I will make a version tomorrow :)

**Pull request merged**
